frr version 9.1.3
frr defaults traditional
hostname as102r2
log file /var/log/frr/frr.log
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 ip address 2.21.0.1/31
exit
!
interface eth1
 ip address 1.102.3.1/31
 ip ospf cost 5
exit
!
interface eth2
 ip address 1.102.3.6/31
 ip ospf cost 10
exit
!
interface dummy0
 ip address 1.102.4.2/32
exit
!
router ospf
 ospf router-id 1.102.4.2
 network 1.102.3.0/31 area 0.0.0.0
 network 1.102.3.6/31 area 0.0.0.0
 network 1.102.4.2/32 area 0.0.0.0
 default-information originate always metric 50 metric-type 1
 redistribute bgp route-map ONLY-AS21
!
router bgp 102
 bgp router-id 1.102.4.2
 neighbor 2.21.0.0 remote-as 21
 neighbor 1.102.4.1 remote-as 102
 neighbor 1.102.4.1 update-source dummy0
 !
 address-family ipv4 unicast
  network 1.102.4.2/32
  aggregate-address 1.102.0.0/20 summary-only
  neighbor 2.21.0.0 route-map FROM-AS21 in
  neighbor 2.21.0.0 route-map TO-AS21 out
  neighbor 1.102.4.1 next-hop-self
 exit-address-family
!
ip prefix-list AS21 seq 5 permit 2.21.0.0/20
!
route-map FROM-AS21 permit 10
 match ip address prefix-list AS21
 set local-preference 200
!
route-map FROM-AS21 permit 20
 set local-preference 50
!
route-map TO-AS21 permit 10
 set as-path prepend 102
!
route-map ONLY-AS21 permit 20
 match ip address prefix-list AS21
!
