frr version 9.1.3
frr defaults traditional
hostname as102r3
log file /var/log/frr/frr.log
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 ip address 1.102.1.1/24
exit
!
interface eth1
 ip address 1.102.3.3/31
 ip ospf cost 10
exit
!
interface eth2
 ip address 1.102.3.7/31
 ip ospf cost 10
exit
!
interface eth3
 ip address 1.102.3.8/31
 ip ospf cost 10
exit
!
interface dummy0
 ip address 1.102.4.3/32
exit
!
router ospf
 network 1.102.1.0/24 area 0.0.0.0
 network 1.102.3.3/31 area 0.0.0.0
 network 1.102.3.7/31 area 0.0.0.0
 network 1.102.3.8/31 area 0.0.0.0
 network 1.102.4.3/32 area 0.0.0.0
!
