# https://ubuntu.com/server/docs/how-to/networking/install-isc-dhcp-server/
# https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcpdconf
subnet 1.102.1.0 netmask 255.255.255.0 {
}
subnet 1.102.2.0 netmask 255.255.255.0 {
  range 1.102.2.10 1.102.2.29;

  option domain-name-servers 1.102.1.2;
  option domain-name "isp102.lab";
  option subnet-mask 255.255.255.0;
  option routers 1.102.2.1;
  option broadcast-address 1.102.2.255;

  default-lease-time 1000;
  max-lease-time 5000;

}
